### PR TITLE
Added UTF-8 encoding to index.html

### PR DESCRIPTION
**Pull request by sidntrivedi**
Added UTF-8 Encoding to index.html. Kindly review.

### CODE REVIEW

**Comment by ryzokuken** [comment]
Looks great! Thanks.

**Comment by sidntrivedi** [comment]
Thanks Sir.. 😊😊

**Comment by ryzokuken** [comment]
@sidntrivedi012 BTW, just noticed: It should've been `<meta charset="utf-8">` instead, but I don't think it will create any issues.

**Comment by sidntrivedi** [comment]
OK Sir.

**Pull request merged**
