### PR TITLE
Minor suggestion!

### PR DESCRIPTION
**Pull request by saranshbarua**
harbor

The colours look different in the screenshot.(The button is not pink!!!)

### CODE REVIEW

**Comment by ryzokuken** [comment]
Umm, could you please also add a screenshot of how the original version looks on linux? I think there must be some cross-OS problem as the current version looks pretty minimalistic on MacOS.

**Comment by ryzokuken** [comment]
screen shot 2018-02-07 at 6 12 34 pm
screen shot 2018-02-07 at 6 12 37 pm

**Comment by saranshbarua** [comment]
Yes, it does not look as good as this on Linux.

**Comment by saranshbarua** [comment]
I pushed the changes directly on to my master branch. My bad..😞

**Comment by ryzokuken** [comment]
I thought so. Let's meet tomorrow and discuss a solid strategy for making it look good across all OSes, what do you say?

**Comment by saranshbarua** [comment]
Sure

On Feb 7, 2018 6:34 PM, "Ujjwal Sharma" <notifications@github.com> wrote:

I thought so. Let's meet tomorrow and discuss a solid strategy for making
it look good across all OSes, what do you say?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ryzokuken/harbor/pull/11#issuecomment-363762435>, or mute
the thread

**Comment by darkHarry** [comment]
suggestion is way better than the original green shade.

**Pull request closed without merging**
